"""empty message

Revision ID: 3f2d7d574a28
Revises: ceec5e4b53bc
Create Date: 2024-07-31 18:17:26.328935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2d7d574a28'
down_revision = 'ceec5e4b53bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_author')
    op.drop_table('Book_List')
    op.drop_table('author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('author_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='author_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Book_List',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Book_List_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Book_List_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('book_author',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='book_author_author_id_fkey'),
    sa.ForeignKeyConstraint(['book_id'], ['Book_List.id'], name='book_author_book_id_fkey')
    )
    # ### end Alembic commands ###
