"""empty message

Revision ID: 7cf529ef032b
Revises: 
Create Date: 2024-08-03 17:37:08.464925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf529ef032b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('library_librarian_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'library_user_table', ['library_user_id'], ['id'])
        batch_op.drop_column('librarian_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('librarian_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('library_librarian_id_fkey', 'library_user_table', ['librarian_id'], ['id'])
        batch_op.drop_column('library_user_id')

    # ### end Alembic commands ###
