"""empty message

Revision ID: ceec5e4b53bc
Revises: 
Create Date: 2024-06-19 18:26:07.201576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceec5e4b53bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Book_List', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkbox_state', sa.Boolean(), nullable=False))
        batch_op.alter_column('finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Book_List', schema=None) as batch_op:
        batch_op.alter_column('finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('checkbox_state')

    # ### end Alembic commands ###
